# ============================================================
# Configurações de conexão com o banco de dados
# Altere os valores de host/porta conforme fornecido pelo professor
# ============================================================

# Host primário (ESCRITA)
db.write.host=127.0.0.1 #trocar aqui
db.write.port=3306
db.write.database=aula-db
db.write.username=root
db.write.password=root

# Réplicas de leitura (READ)
# Adicione quantas réplicas precisar separadas por vírgula
# Formato: host:porta
db.read.replicas=127.0.0.1:3307 #trocar aqui
db.read.database=aula-db
db.read.username=root
db.read.password=root

# Intervalo entre ciclos (milissegundos)
app.cycle.interval.ms=3000

# Quantidade de ciclos (0 = infinito)
app.cycles=0
